In [1]:
import pandas as pd
vendas = pd.read_json('dados_vendas_clientes.json')

<p>O desafio do projeto 1: vendas online será abrir a base de dados com Pandas e aplicar o json_normalize.</p>

In [2]:
vendas

                                        dados_vendas
0  {'Data de venda': '06/06/2022', 'Cliente': ['@...
1  {'Data de venda': '07/06/2022', 'Cliente': ['I...
2  {'Data de venda': '08/06/2022', 'Cliente': ['I...
3  {'Data de venda': '09/06/2022', 'Cliente': ['J...
4  {'Data de venda': '10/06/2022', 'Cliente': ['M...

In [3]:
vendas = pd.json_normalize(vendas['dados_vendas'])
vendas

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

<P><ul>Remover os dados em listas dentro do DataFrame</ul>
<ul>Verificar os tipos de dados;</ul>
<ul>Identificar colunas numéricas;</ul>
<ul>Transformar a coluna numérica para o tipo numérico.</ul>
</P>

In [4]:
vendas = vendas.explode(['Cliente',	'Valor da compra'])
vendas = vendas.reset_index(drop=True)
vendas

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321        R$ 836,5
1     06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2     06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3     06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4     07/06/2022  Isabely JOanes 738       R$ 825,31
5     07/06/2022  Isabely JOanes 738       R$ 168,07
6     07/06/2022  Isabely JOanes 738       R$ 339,18
7     07/06/2022  Isabely JOanes 738       R$ 314,69
8     08/06/2022  Isabely JOanes 738       R$ 682,05
9     08/06/2022    JOãO Gabriel 671       R$ 386,34
10    08/06/2022  Julya meireles 914       R$ 622,65
11    08/06/2022  Julya meireles 914       R$ 630,79
12    09/06/2022  Julya meireles 914        R$ 390,3
13    09/06/2022     MaRIA Julia 444       R$ 759,16
14    09/06/2022     MaRIA Julia 444       R$ 334,47
15    09/06/2022     MaRIA Julia 444       R$ 678,78
16    10/06/2022     MaRIA Julia 444       R$ 314,24
17    10/06/2022     PEDRO PASCO 812       R$ 311,15
18    10/06/2022    Paulo castro 481       R$ 899,16
19    10/06/2022   Thiago fritzz 883       R$ 885,24

In [5]:
vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     str
 1   Cliente          20 non-null     str
 2   Valor da compra  20 non-null     str
dtypes: str(3)
memory usage: 612.0 bytes

In [6]:
vendas['Valor da compra'] = vendas['Valor da compra'].apply(lambda x: x.replace('R$','').replace(',','.').strip())
vendas

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321           836.5
1     06/06/2022  DieGO ARMANDIU 210          573.33
2     06/06/2022  DieGO ARMANDIU 210           392.8
3     06/06/2022  DieGO ARMANDIU 210          512.34
4     07/06/2022  Isabely JOanes 738          825.31
5     07/06/2022  Isabely JOanes 738          168.07
6     07/06/2022  Isabely JOanes 738          339.18
7     07/06/2022  Isabely JOanes 738          314.69
8     08/06/2022  Isabely JOanes 738          682.05
9     08/06/2022    JOãO Gabriel 671          386.34
10    08/06/2022  Julya meireles 914          622.65
11    08/06/2022  Julya meireles 914          630.79
12    09/06/2022  Julya meireles 914           390.3
13    09/06/2022     MaRIA Julia 444          759.16
14    09/06/2022     MaRIA Julia 444          334.47
15    09/06/2022     MaRIA Julia 444          678.78
16    10/06/2022     MaRIA Julia 444          314.24
17    10/06/2022     PEDRO PASCO 812          311.15
18    10/06/2022    Paulo castro 481          899.16
19    10/06/2022   Thiago fritzz 883          885.24

In [7]:
vendas['Valor da compra'] = vendas['Valor da compra'].astype('float64')
vendas['Data de venda'] = pd.to_datetime(vendas['Data de venda'])
vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     datetime64[us]
 1   Cliente          20 non-null     str
 2   Valor da compra  20 non-null     float64
dtypes: datetime64[us](1), float64(1), str(1)
memory usage: 612.0 bytes

In [8]:
vendas

   Data de venda             Cliente  Valor da compra
0     2022-06-06     @ANA _LUCIA 321           836.50
1     2022-06-06  DieGO ARMANDIU 210           573.33
2     2022-06-06  DieGO ARMANDIU 210           392.80
3     2022-06-06  DieGO ARMANDIU 210           512.34
4     2022-07-06  Isabely JOanes 738           825.31
5     2022-07-06  Isabely JOanes 738           168.07
6     2022-07-06  Isabely JOanes 738           339.18
7     2022-07-06  Isabely JOanes 738           314.69
8     2022-08-06  Isabely JOanes 738           682.05
9     2022-08-06    JOãO Gabriel 671           386.34
10    2022-08-06  Julya meireles 914           622.65
11    2022-08-06  Julya meireles 914           630.79
12    2022-09-06  Julya meireles 914           390.30
13    2022-09-06     MaRIA Julia 444           759.16
14    2022-09-06     MaRIA Julia 444           334.47
15    2022-09-06     MaRIA Julia 444           678.78
16    2022-10-06     MaRIA Julia 444           314.24
17    2022-10-06     PEDRO PASCO 812           311.15
18    2022-10-06    Paulo castro 481           899.16
19    2022-10-06   Thiago fritzz 883           885.24

In [10]:
vendas['Cliente'] = vendas['Cliente'].str.replace('[^a-zA-Zà-úÀ-ÚçÇ\s]','',regex=True)
vendas['Cliente'] = vendas['Cliente'].str.lower()
vendas

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\marco\AppData\Local\Temp\ipykernel_8760\1548271065.py:1: SyntaxWarning: invalid escape sequence '\s'
  vendas['Cliente'] = vendas['Cliente'].str.replace('[^a-zA-Zà-úÀ-ÚçÇ\s]','',regex=True)

   Data de venda          Cliente  Valor da compra
0     2022-06-06       ana lucia            836.50
1     2022-06-06  diego armandiu            573.33
2     2022-06-06  diego armandiu            392.80
3     2022-06-06  diego armandiu            512.34
4     2022-07-06  isabely joanes            825.31
5     2022-07-06  isabely joanes            168.07
6     2022-07-06  isabely joanes            339.18
7     2022-07-06  isabely joanes            314.69
8     2022-08-06  isabely joanes            682.05
9     2022-08-06    joão gabriel            386.34
10    2022-08-06  julya meireles            622.65
11    2022-08-06  julya meireles            630.79
12    2022-09-06  julya meireles            390.30
13    2022-09-06     maria julia            759.16
14    2022-09-06     maria julia            334.47
15    2022-09-06     maria julia            678.78
16    2022-10-06     maria julia            314.24
17    2022-10-06     pedro pasco            311.15
18    2022-10-06    paulo castro            899.16
19    2022-10-06   thiago fritzz            885.24

Busque uma forma de visualização de subconjunto que possa contribuir no objetivo do contexto que os dados estão inseridos.

In [12]:
vendas.groupby(vendas['Data de venda'].dt.strftime('%Y-%m'))['Valor da compra'].mean()

Data de venda
2022-06    578.7425
2022-07    411.8125
2022-08    580.4575
2022-09    540.6775
2022-10    602.4475
Name: Valor da compra, dtype: float64